include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = libChameleonAVFoundation
libChameleonAVFoundation_OBJC_FILES = AVAudioPlayer.m AVAudioSession.m
libChameleonAVFoundation_HEADER_FILES = AVAudioPlayer.h AVAudioSession.h AVFoundation.h
libChameleonAVFoundation_HEADER_FILES_INSTALL_DIR = Chameleon/AVFoundation
libChameleonAVFoundation_NEEDS_GUI = yes

include $(GNUSTEP_MAKEFILES)/library.make
